import re

with open('app.js', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Definir TAG_ICONS
TAG_ICONS_BLOCK = 'const TAG_ICONS = { photo: "📷", video: "🎬", audio: "🎙️", writing: "✍️", versus: "⚔️", game: "🎮", sensors: "🧭", economy: "💰", physical: "🏃" };'

# 2. Definir MISSIONS_CONFIG (todas las misiones en un solo objeto)
MISSIONS = {
    # DÍA 1
    "day_1_fam_bet": """{ tag: "writing", day: 1, title: "Apuesta del Aterrizaje", role: "both", xp: 25, location: "Vuelo Internacional ✈️", render: () => `<p class="mission-desc">¡El viaje comienza sobre las nubes! Escribid cada uno 3 locuras que creéis que veréis.</p><input type="text" id="b1"><input type="text" id="b2"><input type="text" id="b3"><button id="btn" class="btn-primary">Sellar</button>`, attachEvents: (role) => { document.getElementById('btn').addEventListener('click', () => submitMission('day_1_fam_bet', {type:'text', data:document.getElementById('b1').value}, role, true)); } }""",
    "day_1_kid9_bingo": """{ tag: "game", day: 1, title: "Bingo Aeroportuario", role: "kid9", xp: 15, location: "Aeropuerto de Osaka (KIX) 🛂", render: () => `<p class="mission-desc">¡Bienvenida a Japón! Encuentra 4 objetos típicos.</p><div class="choice-grid"><button class="btn-secondary b-item">🎎</button><button class="btn-secondary b-item">🚅</button><button class="btn-secondary b-item">🍣</button><button class="btn-secondary b-item">🏮</button></div><button id="btn" class="btn-primary hidden">Bingo!</button>`, attachEvents: () => { document.querySelectorAll('.b-item').forEach(b => b.addEventListener('click', () => { b.classList.toggle('selected'); if(document.querySelectorAll('.b-item.selected').length>=4) document.getElementById('btn').classList.remove('hidden'); })); document.getElementById('btn').addEventListener('click', () => submitMission('day_1_kid9_bingo', {type:'text', data:'Bingo'})); } }""",
    "day_1_kid14_nav": """{ tag: "sensors", day: 1, title: "Navegante de Altura", role: "kid14", xp: 15, location: "A bordo del Boeing 777 🛰️", render: () => `<p class="mission-desc">Monitoriza nuestra llegada. Anota velocidad y usa la brújula.</p><div id="comp">0°</div><input type="number" id="s"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { window.addEventListener('deviceorientation', (e) => { if(e.alpha) document.getElementById('comp').innerText = Math.round(e.alpha)+'°'; }); document.getElementById('btn').addEventListener('click', () => submitMission('day_1_kid14_nav', {type:'text', data:document.getElementById('s').value})); } }""",
    "day_1_kid14_jetlag": """{ tag: "writing", day: 1, title: "Reloj Samurái del Sueño", role: "kid14", xp: 15, location: "Hotel Osaka / Avión 🏮", render: () => `<p class="mission-desc">Sincroniza tu reloj interno (+7h España).</p><input type="time" id="t"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_1_kid14_jetlag', {type:'text', data:document.getElementById('t').value})); } }""",
    
    # DÍA 2
    "day_2_kid9_yokai": """{ tag: "photo", day: 2, title: "Caza del Yōkai Oficial", role: "kid9", xp: 20, location: "Calles de Osaka 🦊", render: () => `<p class="mission-desc">Captura a un Yokai moderno (mascota o cartel manga).</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_2_kid9_yokai', {type:'text', data:'Foto'})); } }""",
    "day_2_kid14_protocol": """{ tag: "versus", day: 2, title: "Protocolo Shōgun", role: "kid14", xp: 20, location: "Red de Metro de Osaka 🗺️", render: () => `<p class="mission-desc">Guía a la familia al hotel.</p><button id="btn" class="btn-primary">Llegamos</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_2_kid14_protocol', {type:'text', data:'Llegada'})); } }""",
    "any_eki_stamp": """{ tag: "photo", day: 2, title: "Eki-Stamps", role: "both", xp: 15, location: "Estaciones de Tren JR 🚅", render: () => `<p class="mission-desc">Busca el sello único de la estación.</p><button id="btn-cam" class="btn-secondary">📸 Foto Sello</button>`, attachEvents: (role) => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('any_eki_stamp', {type:'text', data:'Sello'}, role, true)); } }""",

    # DÍA 3
    "day_3_kid9_foso": """{ tag: "physical", day: 3, title: "Pasos de Gigante", role: "kid9", xp: 15, location: "Fosos del Castillo de Osaka", render: () => `<p class="mission-desc">Cuenta cuántos pasos de gigante necesitas para cruzar el puente.</p><input type="number" id="p"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_3_kid9_foso', {type:'number', data:document.getElementById('p').value})); } }""",
    "day_3_kid14_asalto": """{ tag: "physical", day: 3, title: "El Asalto al Shogun", role: "kid14", xp: 20, location: "Castillo de Osaka", render: () => `<div id="c" style="font-size:2rem;">00:00</div><button id="s">Iniciar</button><button id="e">Parar</button><input id="w"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { let t=0, i=null; document.getElementById('s').addEventListener('click', () => { if(!i) i=setInterval(()=>{t++; document.getElementById('c').innerText=Math.floor(t/60)+':'+(t%60);},1000); }); document.getElementById('e').addEventListener('click', () => clearInterval(i)); document.getElementById('btn').addEventListener('click', () => submitMission('day_3_kid14_asalto', {type:'text', data:document.getElementById('c').innerText})); } }""",

    # DÍA 4
    "day_4_kid9_cangrejo": """{ tag: "physical", day: 4, title: "El Paso del Cangrejo", role: "kid9", xp: 15, location: "Puente Sorihashi", render: () => `<button id="b1">🦀 Lado</button><button id="b2">🚶 Frente</button>`, attachEvents: () => { document.getElementById('b1').addEventListener('click', () => submitMission('day_4_kid9_cangrejo', {type:'text', data:'Cangrejo'})); document.getElementById('b2').addEventListener('click', () => submitMission('day_4_kid9_cangrejo', {type:'text', data:'Frente'})); } }""",
    "day_4_kid14_kuromon": """{ tag: "physical", day: 4, title: "Rastreador Kuromon", role: "kid14", xp: 15, location: "Kuromon", render: () => `<input type="number" id="n"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_4_kid14_kuromon', {type:'number', data:document.getElementById('n').value})); } }""",

    # DÍA 5
    "day_5_kid9_galax": """{ tag: "physical", day: 5, title: "Galaxia Ciervos", role: "kid9", xp: 20, location: "Parque de Nara", render: () => `<div id="v">0</div><button id="p">+</button><button id="m">-</button><button id="b" class="btn-primary">Calcular</button>`, attachEvents: () => { let c=0; document.getElementById('p').addEventListener('click', () => {c++; document.getElementById('v').innerText=c;}); document.getElementById('b').addEventListener('click', () => submitMission('day_5_kid9_galax', {type:'text', data:c*6})); } }""",
    "day_5_kid14_suerte": """{ tag: "physical", day: 5, title: "Guardián de la Suerte", role: "kid14", xp: 20, location: "Todai-ji", render: () => `<input type="number" id="n1"><input type="number" id="n2"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_5_kid14_suerte', {type:'text', data:document.getElementById('n1').value})); } }""",

    # DÍA 6
    "day_6_kid9_huida": """{ tag: "physical", day: 6, title: "Huida Ninja", role: "kid9", xp: 20, location: "Nijo", render: () => `<button id="b1">A</button><button id="b2">B</button>`, attachEvents: () => { document.getElementById('b1').addEventListener('click', () => submitMission('day_6_kid9_huida', {type:'text', data:'A'})); } }""",
    "day_6_kid14_anillo": """{ tag: "physical", day: 6, title: "Anillo Imperial", role: "kid14", xp: 20, location: "Palacio Imperial", render: () => `<div id="c">00:00</div><button id="s">S</button><button id="e">E</button><input type="number" id="n"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_6_kid14_anillo', {type:'text', data:'OK'})); } }""",
    "day_6_kid9_ninja_steps": """{ tag: "game", day: 6, title: "Pasos de Ninja (G)", role: "kid9", xp: 20, location: "Pasillos del Castillo Nijo 👣", render: () => `<div id="ninja-game" class="game-container" style="height:300px;"><div class="rhythm-zone"></div><div id="ninja-score" style="position:absolute;top:10px;right:10px;">0/5</div></div><button id="btn-start" class="btn-primary">Empezar</button><button id="btn-victory" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const cont=document.getElementById('ninja-game'); const sc=document.getElementById('ninja-score'); const btnS=document.getElementById('btn-start'); const btnV=document.getElementById('btn-victory'); let score=0; let active=false; let foots=[]; const spawn=() => { if(!active) return; const f=document.createElement('div'); f.innerHTML='👣'; f.style.position='absolute'; f.style.top='-50px'; f.style.left='50%'; f.style.fontSize='2rem'; f.dataset.hit='false'; cont.appendChild(f); foots.push({el:f, top:-50}); setTimeout(spawn, 1500); }; const loop=() => { if(!active) return; foots.forEach((f,i) => { f.top+=3; f.el.style.top=f.top+'px'; if(f.top>300){f.el.remove(); foots.splice(i,1);} }); requestAnimationFrame(loop); }; cont.addEventListener('touchstart', () => { foots.forEach(f => { if(f.top>200 && f.top<280 && f.el.dataset.hit==='false'){ f.el.dataset.hit='true'; score++; sc.innerText=score+'/5'; if(score>=5){active=false; btnV.classList.remove('hidden');} } }); }); btnS.addEventListener('click', () => { btnS.classList.add('hidden'); active=true; spawn(); loop(); }); btnV.addEventListener('click', () => submitMission('day_6_kid9_ninja_steps', {type:'text', data:'Superado'})); } }""",
    "day_6_kid9_ruisenor": """{ tag: "audio", day: 6, title: "Suelo Ruiseñor", role: "kid9", xp: 15, location: "Nijo", render: () => `<p class="mission-desc">Graba el chirrido real.</p><button id="btn-cam" class="btn-secondary">🎤 Grabar</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_6_kid9_ruisenor', {type:'text', data:'Audio'})); } },
    "day_6_kid9_ruisenor_video": """{ tag: "video", day: 6, title: "El Espía del Suelo", role: "kid9", xp: 20, location: "Nijo", render: () => `<p class="mission-desc">Vídeo 10s y descripción.</p><input type="file" accept="video/*" capture="environment" id="v"><input type="text" id="d" placeholder="Me recuerda a..."><button id="b" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('b').addEventListener('click', () => submitMission('day_6_kid9_ruisenor_video', {type:'text', data:document.getElementById('d').value})); } }""",

    # DÍA 7
    "day_7_kid9_pilar": """{ tag: "physical", day: 7, title: "Guardián de Piedra", role: "kid9", xp: 15, location: "Kiyomizu-dera", render: () => `<button id="b1">Toca</button><button id="b2">Casi</button>`, attachEvents: () => { document.getElementById('b1').addEventListener('click', () => submitMission('day_7_kid9_pilar', {type:'text', data:'Toca'})); } }""",
    "day_7_kid14_escaleras": """{ tag: "physical", day: 7, title: "Conquista de las Escaleras", role: "kid14", xp: 20, location: "Subida a Kiyomizu", render: () => `<input type="number" id="n"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_7_kid14_escaleras', {type:'number', data:document.getElementById('n').value})); } }""",
    "day_7_kid14_anti_seismic": """{ tag: "game", day: 7, title: "Anti-Sismo (G)", role: "kid14", xp: 20, location: "Kiyomizu-dera 🏗️", render: () => `<div class="level-container"><div id="bub" class="bubble"></div></div><button id="btn" class="btn-primary">Empezar</button><button id="btnV" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const b=document.getElementById('bub'); const btnS=document.getElementById('btn'); const btnV=document.getElementById('btnV'); let t=15; let act=false; window.addEventListener('deviceorientation', (e) => { if(act) b.style.transform = 'translate(calc(-50% + '+(e.gamma*2)+'px), calc(-50% + '+(e.beta*2)+'px))'; }); btnS.addEventListener('click', () => { act=true; btnS.classList.add('hidden'); setInterval(()=> { if(act){t--; if(t<=0){act=false; btnV.classList.remove('hidden');}} },1000); }); btnV.addEventListener('click', () => submitMission('day_7_kid14_anti_seismic', {type:'text', data:'Estable'})); } }""",
    "day_7_fam_gion": """{ tag: "photo", day: 7, title: "Código Geisha", role: "both", xp: 15, location: "Gion", render: () => `<p class="mission-desc">Foto en Gion.</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: (role) => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_7_fam_gion', {type:'text', data:'Foto'}, role, true)); } }""",
    "day_7_kid14_guia": """{ tag: "video", day: 7, title: "Guía en 60s", role: "kid14", xp: 20, location: "Gion", render: () => `<div id="timer">60</div><input type="file" accept="video/*" capture="environment" id="v"><button id="b" class="btn-primary">Enviar</button>`, attachEvents: () => { let s=60; setInterval(()=>{if(s>0){s--; document.getElementById('timer').innerText=s;}},1000); document.getElementById('b').addEventListener('click', () => submitMission('day_7_kid14_guia', {type:'text', data:'Guía'})); } }""",

    # DÍA 8
    "day_8_kid9_pose": """{ tag: "photo", day: 8, title: "Trono de Piedra", role: "kid9", xp: 20, location: "Otagi", render: () => `<input type="file" capture="environment"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_8_kid9_pose', {type:'text', data:'Foto'})); } }""",
    "day_8_kid14_bosque": """{ tag: "physical", day: 8, title: "Bosque de Bambú 2.7km", role: "kid14", xp: 20, location: "Arashiyama", render: () => `<input type="checkbox" id="c1"><input type="checkbox" id="c2"><input type="checkbox" id="c3"><input type="number" id="n"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_8_kid14_bosque', {type:'text', data:'OK'})); } }""",
    "day_8_kid14_wave_sync": """{ tag: "game", day: 8, title: "Sincro Ondas (G)", role: "kid14", xp: 20, location: "Arashiyama 🎋", render: () => `<canvas id="wc" class="wave-canvas"></canvas><input type="range" id="sl" min="0.01" max="0.1" step="0.01"><button id="btn" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const c=document.getElementById('wc'); const ctx=c.getContext('2d'); const s=document.getElementById('sl'); const b=document.getElementById('btn'); const loop=() => { ctx.clearRect(0,0,c.width,c.height); ctx.beginPath(); ctx.strokeStyle='#2ecc71'; for(let x=0;x<c.width;x++) ctx.lineTo(x,100+40*Math.sin(x*0.05)); ctx.stroke(); ctx.beginPath(); ctx.strokeStyle='#e74c3c'; for(let x=0;x<c.width;x++) ctx.lineTo(x,100+40*Math.sin(x*s.value)); ctx.stroke(); if(Math.abs(s.value-0.05)<0.01) b.classList.remove('hidden'); requestAnimationFrame(loop); }; loop(); b.addEventListener('click', () => submitMission('day_8_kid14_wave_sync', {type:'text', data:'Sincro'})); } }""",

    # DÍA 9
    "day_9_kid9_zorros": """{ tag: "physical", day: 9, title: "Escalada de los Zorros", role: "kid9", xp: 25, location: "Fushimi Inari", render: () => `<div id="t">10:00</div><button id="s">Empezar</button><input id="x" class="hidden"><button id="btn" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_9_kid9_zorros', {type:'text', data:'OK'})); } }""",
    "day_9_kid14_ave": """{ tag: "physical", day: 9, title: "Postura del Ave", role: "kid14", xp: 20, location: "Kinkaku-ji", render: () => `<div id="c">0s</div><button id="s">S</button><button id="e">E</button>`, attachEvents: () => { document.getElementById('e').addEventListener('click', () => submitMission('day_9_kid14_ave', {type:'text', data:'OK'})); } }""",
    "day_9_kid9_scratch": """{ tag: "game", day: 9, title: "Limpia Reflejo (G)", role: "kid9", xp: 20, location: "Kinkaku-ji 🟡", render: () => `<div class="scratch-container"><canvas id="sc" class="scratch-canvas"></canvas></div><button id="btn" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const c=document.getElementById('sc'); const ctx=c.getContext('2d'); const b=document.getElementById('btn'); ctx.fillStyle='#78909c'; ctx.fillRect(0,0,c.width,c.height); let s=0; c.addEventListener('touchmove', (e) => { ctx.globalCompositeOperation='destination-out'; ctx.beginPath(); ctx.arc(e.touches[0].clientX-c.offsetLeft, e.touches[0].clientY-c.offsetTop, 20, 0, 6.28); ctx.fill(); s++; if(s>50) b.classList.remove('hidden'); }); b.addEventListener('click', () => submitMission('day_9_kid9_scratch', {type:'text', data:'OK'})); } }""",
    "day_9_kid14_torii": """{ tag: "game", day: 9, title: "Laberinto Torii (G)", role: "kid14", xp: 25, location: "Fushimi Inari ⛩️", render: () => `<div class="torii-grid">${Array(9).fill(0).map((_,i)=>`<div class="tp" data-r="0" style="border:1px solid #ccc; height:60px;">⛩️</div>`).join('')}</div><button id="btn" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const ps=document.querySelectorAll('.tp'); const b=document.getElementById('btn'); let count=0; ps.forEach(p => p.addEventListener('click', () => { p.dataset.r=parseInt(p.dataset.r)+90; p.style.transform='rotate('+p.dataset.r+'deg)'; count++; if(count>5) b.classList.remove('hidden'); })); b.addEventListener('click', () => submitMission('day_9_kid14_torii', {type:'text', data:'OK'})); } }""",

    # DÍA 10
    "day_10_kid9_dragon": """{ tag: "physical", day: 10, title: "Dragón del Mercado", role: "kid9", xp: 15, location: "Mercado Nishiki", render: () => `<input type="number" id="n"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_10_kid9_dragon', {type:'number', data:document.getElementById('n').value})); } }""",
    "day_10_kid14_milla": """{ tag: "physical", day: 10, title: "Milla del Samurái", role: "kid14", xp: 20, location: "Ribera del Río Kamo", render: () => `<div id="c">00:00</div><button id="s">S</button><button id="e">E</button><input id="x"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_10_kid14_milla', {type:'text', data:'OK'})); } }""",
    "day_10_kid9_bento": """{ tag: "game", day: 10, title: "Maestro Bento (G)", role: "kid9", xp: 20, location: "Mercado Nishiki 🍱", render: () => `<div class="bento-tray"><div class="bento-slot">🍱</div></div><div class="ingredient" style="font-size:2rem;">🍱</div><button id="btn" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const ing=document.querySelector('.ingredient'); const b=document.getElementById('btn'); ing.addEventListener('touchmove', (e) => { ing.style.position='fixed'; ing.style.left=e.touches[0].clientX+'px'; ing.style.top=e.touches[0].clientY+'px'; b.classList.remove('hidden'); }); b.addEventListener('click', () => submitMission('day_10_kid9_bento', {type:'text', data:'OK'})); } }"""
}

# Reconstruir el objeto JS
config_lines = []
for k, v in MISSIONS.items():
    # Extraer el día del ID si no está definido en el string (para asegurar consistencia)
    m = re.search(r'day_(\d+)', k)
    day = int(m.group(1)) if m else 0
    # Añadir el día explícitamente si falta o es incorrecto (aunque aquí ya están bien)
    config_lines.append(f'    "{k}": {v}')

new_config_block = "const MISSIONS_CONFIG = {\n" + ",\n".join(config_lines) + "\n};"

# 3. Reemplazar TAG_ICONS y MISSIONS_CONFIG (desde el inicio de TAG_ICONS hasta el final de MISSIONS_CONFIG)
# En el archivo actual, TAG_ICONS está en la línea 181 y MISSIONS_CONFIG termina en 397
# Buscamos el patrón
tag_start = content.find('const TAG_ICONS =')
config_end = content.find('};', content.find('const MISSIONS_CONFIG =')) + 2

# El problema es que hay múltiples }; por la corrupción. 
# Buscaremos el último }; antes de "function switchView"
switch_view_start = content.find('function switchView')
config_end_real = content.rfind('};', 0, switch_view_start) + 2

full_replacement = TAG_ICONS_BLOCK + "\n" + new_config_block

new_content = content[:tag_start] + full_replacement + content[config_end_real:]

with open('app.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("MISSIONS_CONFIG y TAG_ICONS reconstruidos desde cero.")
