import re

with open('app.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Definición de misiones (Combinando las 65 anteriores + actualizaciones de Días 6-9)
# He optimizado la lógica de las misiones Versus y Cooperativas
MISSIONS = {
    # DÍA 1-5 (Se mantienen igual)
    "day_1_fam_bet": """{ tag: "writing", day: 1, title: "Apuesta del Aterrizaje", role: "both", xp: 25, location: "Avión / Aeropuerto", render: () => `<p class="mission-desc">Escribe 3 locuras que crees que verás en Japón.</p><input type="text" id="b1" placeholder="1..."><input type="text" id="b2" placeholder="2..."><input type="text" id="b3" placeholder="3..."><button id="btn" class="btn-primary" style="width:100%">Sellar</button>`, attachEvents: (role) => { document.getElementById('btn').addEventListener('click', () => submitMission('day_1_fam_bet', {type:'text', data:document.getElementById('b1').value}, role, true)); } }""",
    "day_1_kid9_bingo": """{ tag: "game", day: 1, title: "Bingo Aeroportuario", role: "kid9", xp: 15, location: "Aeropuerto", render: () => `<p class="mission-desc">Encuentra 4 objetos.</p><div class="choice-grid"><button class="btn-secondary b-item">🎎</button><button class="btn-secondary b-item">🍵</button><button class="btn-secondary b-item">🚅</button><button class="btn-secondary b-item">🍣</button><button class="btn-secondary b-item">🏮</button><button class="btn-secondary b-item">🐱</button></div><button id="btn" class="btn-primary hidden" style="width:100%">Bingo!</button>`, attachEvents: () => { document.querySelectorAll('.b-item').forEach(b => b.addEventListener('click', () => { b.classList.toggle('selected'); if(document.querySelectorAll('.b-item.selected').length>=4) document.getElementById('btn').classList.remove('hidden'); })); document.getElementById('btn').addEventListener('click', () => submitMission('day_1_kid9_bingo', {type:'text', data:'Bingo completado'})); } }""",
    "day_1_kid14_nav": """{ tag: "sensors", day: 1, title: "Navegante de Altura", role: "kid14", xp: 15, location: "Avión", render: () => `<p class="mission-desc">Anota velocidad y usa la brújula.</p><div id="compass" style="font-size:2rem; text-align:center;">0°</div><input type="number" id="s" placeholder="km/h"><button id="btn" class="btn-primary" style="width:100%">Enviar</button>`, attachEvents: () => { window.addEventListener('deviceorientation', (e) => { if(e.alpha) document.getElementById('compass').innerText = Math.round(e.alpha)+'°'; }); document.getElementById('btn').addEventListener('click', () => submitMission('day_1_kid14_nav', {type:'text', data:document.getElementById('s').value + ' km/h'})); } }""",
    "day_1_kid14_jetlag": """{ tag: "writing", day: 1, title: "Reloj Samurái del Sueño", role: "kid14", xp: 15, location: "Avión / Hotel", render: () => `<p class="mission-desc">Calcula tu hora de dormir (+7h).</p><input type="time" id="t"><button id="btn" class="btn-primary" style="width:100%">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_1_kid14_jetlag', {type:'text', data:document.getElementById('t').value})); } }""",
    "day_2_kid9_yokai": """{ tag: "photo", day: 2, title: "Caza del Yōkai Oficial", role: "kid9", xp: 20, location: "Calle", render: () => `<p class="mission-desc">Foto de mascota o cartel manga.</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_2_kid9_yokai', {type:'text', data:'Yokai capturado'})); } }""",
    "any_eki_stamp": """{ tag: "photo", day: 2, title: "Coleccionista de Eki-Stamps", role: "both", xp: 15, location: "Estaciones", render: () => `<p class="mission-desc">Busca el sello de la estación.</p><button id="btn-cam" class="btn-secondary">📸 Foto Sello</button>`, attachEvents: (role) => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('any_eki_stamp', {type:'text', data:'Sello'}, role, true)); } }""",
    "day_2_kid14_protocol": """{ tag: "versus", day: 2, title: "Protocolo Shōgun", role: "kid14", xp: 20, location: "Metro / Tren", render: () => `<p class="mission-desc">Guía a la familia al hotel.</p><button id="btn" class="btn-primary" style="width:100%">Llegamos</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_2_kid14_protocol', {type:'text', data:'OK'})); } }""",
    "day_3_kid14_architect": """{ tag: "writing", day: 3, title: "Arquitecto del Castillo", role: "kid14", xp: 20, location: "Castillo Osaka", render: () => `<p class="mission-desc">Mide distancia con Maps Satélite.</p><input type="number" id="d" placeholder="Metros..."><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_3_kid14_architect', {type:'number', data:document.getElementById('d').value})); } }""",
    "day_3_kid14_audio": """{ tag: "audio", day: 3, title: "Jingle de Estación", role: "kid14", xp: 15, location: "Estación", render: () => `<p class="mission-desc">Graba el jingle del tren.</p><button id="btn-cam" class="btn-secondary">🎤 Grabar</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_3_kid14_audio', {type:'text', data:'Audio'})); } }""",
    "day_3_kid14_filtro": """{ tag: "photo", day: 3, title: "Filtro Cyberpunk", role: "kid14", xp: 10, location: "Umeda Sky", render: () => `<p class="mission-desc">Foto con filtro neón.</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_3_kid14_filtro', {type:'text', data:'Foto'})); } }""",
    "day_3_kid9_glico": """{ tag: "photo", day: 3, title: "Glico Man", role: "kid9", xp: 10, location: "Dotonbori", render: () => `<p class="mission-desc">Imita al Glico Man.</p><button id="btn-cam" class="btn-secondary">📸 Selfie</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_3_kid9_glico', {type:'text', data:'Glico'})); } }""",
    "day_3_kid9_ninja": """{ tag: "photo", day: 3, title: "Ninja de las Sombras", role: "kid9", xp: 10, location: "Jardines", render: () => `<p class="mission-desc">Foto de tu sombra ninja.</p><button id="btn-cam" class="btn-secondary">📸 Sombra</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_3_kid9_ninja', {type:'text', data:'Sombra'})); } }""",
    "day_3_kid9_puente": """{ tag: "writing", day: 3, title: "Puente del Castillo", role: "kid9", xp: 15, location: "Castillo", render: () => `<p class="mission-desc">Cuenta los pasos del puente.</p><input type="number" id="p"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_3_kid9_puente', {type:'number', data:document.getElementById('p').value})); } }""",
    "day_3_kid14_tribunal": """{ tag: "photo", day: 3, title: "Tribunal del Cartel", role: "kid14", xp: 15, location: "Dotonbori", render: () => `<p class="mission-desc">Foto del cartel más exagerado.</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_3_kid14_tribunal', {type:'text', data:'Cartel'})); } }""",
    "day_3_kid9_umeda": """{ tag: "photo", day: 3, title: "Umeda Sky (Superhéroe)", role: "kid9", xp: 10, location: "Umeda Sky", render: () => `<p class="mission-desc">Sujeta el edificio.</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_3_kid9_umeda', {type:'text', data:'Superheroe'})); } }""",
    "day_4_kid9_bestiario": """{ tag: "writing", day: 4, title: "Bestiario Kuromon", role: "kid9", xp: 15, location: "Kuromon", render: () => `<p class="mission-desc">Pon nombre a un animal marino alienígena.</p><input type="text" id="n"><button id="btn" class="btn-primary">Bautizar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_4_kid9_bestiario', {type:'text', data:document.getElementById('n').value})); } }""",
    "day_4_kid14_cuchillo": """{ tag: "writing", day: 4, title: "El Cuchillo Samurái", role: "kid14", xp: 10, location: "Doguyasuji", render: () => `<p class="mission-desc">Elige cuchillo y plato estrella.</p><input type="text" id="p"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_4_kid14_cuchillo', {type:'text', data:document.getElementById('p').value})); } }""",
    "day_4_kid14_conbini": """{ tag: "economy", day: 4, title: "Reto 500 Yenes", role: "kid14", xp: 15, location: "Lawson", render: () => `<p class="mission-desc">Gasta max 500¥.</p><input type="number" id="v"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_4_kid14_conbini', {type:'number', data:document.getElementById('v').value})); } }""",
    "day_4_kid14_isshinji": """{ tag: "writing", day: 4, title: "Secreto Isshinji", role: "kid14", xp: 15, location: "Isshinji", render: () => `<p class="mission-desc">¿De qué están hechas las estatuas?</p><input type="text" id="a"><button id="btn" class="btn-primary">Responder</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_4_kid14_isshinji', {type:'text', data:document.getElementById('a').value})); } }""",
    "day_4_kid9_gachapon": """{ tag: "game", day: 4, title: "Gachapon", role: "kid9", xp: 10, location: "Tiendas", render: () => `<p class="mission-desc">Prueba suerte.</p><button id="btn" class="btn-primary">Girar!</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_4_kid9_gachapon', {type:'text', data:'Gacha'})); } }""",
    "day_4_fam_yakiniku": """{ tag: "versus", day: 4, title: "Maestro Yakiniku", role: "both", xp: 20, location: "Restaurante", render: () => `<p class="mission-desc">Trabajo en equipo en la barbacoa.</p><button id="btn" class="btn-primary">Completado</button>`, attachEvents: (role) => { document.getElementById('btn').addEventListener('click', () => submitMission('day_4_fam_yakiniku', {type:'text', data:'OK'}, role, true)); } }""",
    "day_4_kid14_meditacion": """{ tag: "photo", day: 4, title: "Meditación Zen", role: "kid14", xp: 15, location: "Namba Parks", render: () => `<p class="mission-desc">Foto sin gente.</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_4_kid14_meditacion', {type:'text', data:'Foto'})); } }""",
    "day_4_kid9_vending": """{ tag: "photo", day: 4, title: "Ruleta Vending", role: "kid9", xp: 15, location: "Calle", render: () => `<p class="mission-desc">Busca la bebida indicada.</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_4_kid9_vending', {type:'text', data:'Foto'})); } }""",
    "day_4_fam_kuromon": """{ tag: "economy", day: 4, title: "Subasta Kuromon", role: "both", xp: 20, location: "Kuromon", render: () => `<p class="mission-desc">Menú ideal 1000¥.</p><textarea id="t"></textarea><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: (role) => { document.getElementById('btn').addEventListener('click', () => submitMission('day_4_fam_kuromon', {type:'text', data:document.getElementById('t').value}, role, true)); } }""",
    "day_5_kid14_kanji": """{ tag: "writing", day: 5, title: "Caligrafía Zen", role: "kid14", xp: 15, location: "Nara", render: () => `<p class="mission-desc">Dibuja Kanji.</p><canvas id="c" style="border:1px solid #ccc; height:200px; width:100%;"></canvas><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_5_kid14_kanji', {type:'text', data:'Kanji'})); } }""",
    "day_5_kid9_deer": """{ tag: "video", day: 5, title: "Coreógrafo Ciervos", role: "kid9", xp: 25, location: "Nara", render: () => `<p class="mission-desc">Vídeo ciervo divertido.</p><button id="btn-cam" class="btn-secondary">🎥 Grabar</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_5_kid9_deer', {type:'text', data:'Video'})); } }""",
    "day_5_kid9_silence": """{ tag: "game", day: 5, title: "Control Monje", role: "kid9", xp: 20, location: "Buda", render: () => `<p class="mission-desc">20s mentales.</p><button id="btn" class="btn-primary">Empezar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_5_kid9_silence', {type:'text', data:'20s'})); } }""",
    "day_5_kid14_rascacielos": """{ tag: "writing", day: 5, title: "Rascacielos Madera", role: "kid14", xp: 10, location: "Todai-ji", render: () => `<p class="mission-desc">¿Cuántos pisos modernos?</p><input type="number" id="n"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_5_kid14_rascacielos', {type:'number', data:document.getElementById('n').value})); } }""",
    "day_5_kid9_embajador": """{ tag: "photo", day: 5, title: "Embajador Ciervos", role: "kid9", xp: 20, location: "Nara", render: () => `<p class="mission-desc">Selfie con 3 ciervos.</p><button id="btn-cam" class="btn-secondary">📸 Selfie</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_5_kid9_embajador', {type:'text', data:'Selfie'})); } }""",
    "day_5_kid14_eng": """{ tag: "writing", day: 5, title: "Ingeniero Todai-ji", role: "kid14", xp: 20, location: "Todai-ji", render: () => `<p class="mission-desc">Cálculo área base.</p><input type="text" id="a"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_5_kid14_eng', {type:'text', data:document.getElementById('a').value})); } }""",
    "day_5_kid9_buda": """{ tag: "game", day: 5, title: "Iluminación Buda", role: "kid9", xp: 15, location: "Todai-ji", render: () => `<p class="mission-desc">Pilar o deseo.</p><button id="btn" class="btn-primary">Hecho</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_5_kid9_buda', {type:'text', data:'Hecho'})); } }""",
    "day_5_kid14_geographic": """{ tag: "photo", day: 5, title: "Nara Geographic", role: "kid14", xp: 15, location: "Nara", render: () => `<p class="mission-desc">Foto ciervo con titular.</p><input type="text" id="t"><button id="btn" class="btn-primary">Publicar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_5_kid14_geographic', {type:'text', data:document.getElementById('t').value})); } }""",

    # DÍA 6-9 ACTUALIZADOS
    "day_6_fam_decreto": """{ tag: "versus", day: 6, title: "El Duelo del Decreto", role: "both", xp: 25, location: "Palacio Imperial", render: () => `<div id="v-p1"><p>Escribid vuestros decretos en secreto.</p><input type="password" id="d9" placeholder="Niña..."><input type="password" id="d14" placeholder="Niño..."><button id="btn-r" class="btn-primary">Revelar</button></div><div id="v-p2" class="hidden"><p id="res"></p><button id="btn-s" class="btn-primary">Enviar al Juez</button></div>`, attachEvents: () => { const btnR=document.getElementById('btn-r'); btnR.addEventListener('click', () => { document.getElementById('res').innerText = '9: ' + document.getElementById('d9').value + ' | 14: ' + document.getElementById('d14').value; document.getElementById('v-p1').classList.add('hidden'); document.getElementById('v-p2').classList.remove('hidden'); }); document.getElementById('btn-s').addEventListener('click', () => submitMission('day_6_fam_decreto', {type:'text', data:'Duelo OK'}, 'both', true)); } }""",
    "day_6_kid14_edicto": """{ tag: "writing", day: 6, title: "Edicto Imperial", role: "kid14", xp: 15, location: "Palacio", render: () => `<p class="mission-desc">Escribe un decreto absurdo.</p><textarea id="t"></textarea><button id="btn" class="btn-primary">Proclamar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_6_kid14_edicto', {type:'text', data:document.getElementById('t').value})); } }""",
    "day_6_kid9_jardin": """{ tag: "writing", day: 6, title: "Jardín Nubes", role: "kid9", xp: 15, location: "Palacio", render: () => `<p class="mission-desc">Describe el pino más raro.</p><input type="text" id="t"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_6_kid9_jardin', {type:'text', data:document.getElementById('t').value})); } }""",
    "day_6_kid9_ruisenor": """{ tag: "audio", day: 6, title: "Suelo Ruiseñor", role: "kid9", xp: 15, location: "Nijo", render: () => `<p class="mission-desc">Graba el chirrido real.</p><button id="btn-cam" class="btn-secondary">🎤 Grabar</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_6_kid9_ruisenor', {type:'text', data:'Audio'})); } }""",
    "day_6_kid9_ruisenor_video": """{ tag: "video", day: 6, title: "El Espía del Suelo", role: "kid9", xp: 20, location: "Nijo", render: () => `<p class="mission-desc">Vídeo 10s y descripción.</p><input type="file" accept="video/*" capture="environment" id="v"><input type="text" id="d" placeholder="Me recuerda a..."><button id="b" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('b').addEventListener('click', () => submitMission('day_6_kid9_ruisenor_video', {type:'text', data:document.getElementById('d').value})); } }""",
    "day_6_kid14_ninja_plan": """{ tag: "writing", day: 6, title: "Plan Infiltración Ninja", role: "kid14", xp: 15, location: "Nijo", render: () => `<p class="mission-desc">Escribe tu plan (2 frases).</p><textarea id="t"></textarea><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_6_kid14_ninja_plan', {type:'text', data:document.getElementById('t').value})); } }""",
    "day_6_kid14_tiempo": """{ tag: "photo", day: 6, title: "Viaje Tiempo", role: "kid14", xp: 15, location: "Sannenzaka", render: () => `<p class="mission-desc">Foto época 1600.</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_6_kid14_tiempo', {type:'text', data:'Foto'})); } }""",
    "day_6_kid14_foto_1600": """{ tag: "writing", day: 6, title: "Fotógrafo de 1600", role: "kid14", xp: 20, location: "Sannenzaka", render: () => { const dep=gameState.kid14.missions['day_6_kid14_tiempo']; if(!dep || dep.status!=='approved') return `<p>🔒 Completa "Viaje Tiempo" primero.</p>`; return `<textarea id="h" placeholder="Contexto histórico..."></textarea><button id="b" class="btn-primary">Enviar</button>`; }, attachEvents: () => { const b=document.getElementById('b'); if(b) b.addEventListener('click', () => submitMission('day_6_kid14_foto_1600', {type:'text', data:document.getElementById('h').value})); } }""",
    "day_6_kid9_ninja_steps": """{ tag: "game", day: 6, title: "Pasos de Ninja (G)", role: "kid9", xp: 20, location: "Nijo", render: () => `<div id="ninja-game" class="game-container" style="height:300px;"><div class="rhythm-zone"></div><div id="ninja-score" style="position:absolute;top:10px;right:10px;">0/5</div></div><button id="btn-start" class="btn-primary">Empezar</button><button id="btn-victory" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const cont=document.getElementById('ninja-game'); const sc=document.getElementById('ninja-score'); const btnS=document.getElementById('btn-start'); const btnV=document.getElementById('btn-victory'); let score=0; let active=false; let foots=[]; const spawn=() => { if(!active) return; const f=document.createElement('div'); f.innerHTML='👣'; f.style.position='absolute'; f.style.top='-50px'; f.style.left='50%'; f.style.fontSize='2rem'; f.dataset.hit='false'; cont.appendChild(f); foots.push({el:f, top:-50}); setTimeout(spawn, 1500); }; const loop=() => { if(!active) return; foots.forEach((f,i) => { f.top+=3; f.el.style.top=f.top+'px'; if(f.top>300){f.el.remove(); foots.splice(i,1);} }); requestAnimationFrame(loop); }; cont.addEventListener('touchstart', () => { foots.forEach(f => { if(f.top>200 && f.top<280 && f.el.dataset.hit==='false'){ f.el.dataset.hit='true'; score++; sc.innerText=score+'/5'; if(score>=5){active=false; btnV.classList.remove('hidden');} } }); }); btnS.addEventListener('click', () => { btnS.classList.add('hidden'); active=true; spawn(); loop(); }); btnV.addEventListener('click', () => submitMission('day_6_kid9_ninja_steps', {type:'text', data:'Superado'})); } }""",
    
    "day_7_fam_gion": """{ tag: "photo", day: 7, title: "Código Geisha", role: "both", xp: 15, location: "Gion", render: () => `<p class="mission-desc">Foto farolillo iluminado.</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: (role) => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_7_fam_gion', {type:'text', data:'Foto'}, role, true)); } }""",
    "day_7_kid14_guia": """{ tag: "video", day: 7, title: "Guía en 60s", role: "kid14", xp: 20, location: "Gion", render: () => `<div id="timer">60</div><input type="file" accept="video/*" capture="environment" id="v"><button id="b" class="btn-primary">Enviar</button>`, attachEvents: () => { let s=60; setInterval(()=>{if(s>0){s--; document.getElementById('timer').innerText=s;}},1000); document.getElementById('b').addEventListener('click', () => submitMission('day_7_kid14_guia', {type:'text', data:'Guía'})); } }""",
    "day_7_kid9_tea": """{ tag: "sensors", day: 7, title: "Té Shogun", role: "kid9", xp: 15, location: "Sannenzaka", render: () => `<p class="mission-desc">Baja plano como una bandeja.</p><button id="btn" class="btn-primary">Empezar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_7_kid9_tea', {type:'text', data:'OK'})); } }""",
    "day_7_kid9_force": """{ tag: "photo", day: 7, title: "Fuerza Benkei", role: "kid9", xp: 15, location: "Kiyomizu", render: () => `<p class="mission-desc">Foto levantando armas Benkei.</p><button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_7_kid9_force', {type:'text', data:'Foto'})); } }""",
    "day_7_fam_stones": """{ tag: "photo", day: 7, title: "Piedras Destino", role: "both", xp: 10, location: "Jishu Shrine", render: () => `<p class="mission-desc">Selfie ojos cerrados entre piedras.</p><button id="btn-cam" class="btn-secondary">📸 Selfie</button>`, attachEvents: (role) => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_7_fam_stones', {type:'text', data:'Selfie'}, role, true)); } }""",
    "day_7_fam_otowa": """{ tag: "versus", day: 7, title: "Reto Agua Sagrada", role: "both", xp: 30, location: "Kiyomizu", render: () => `<p>Elegid un don en secreto.</p><select id="s9"><option value="estudios">Estudios</option><option value="amor">Amor</option><option value="salud">Salud</option></select><select id="s14"><option value="estudios">Estudios</option><option value="amor">Amor</option><option value="salud">Salud</option></select><button id="b" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('b').addEventListener('click', () => submitMission('day_7_fam_otowa', {type:'text', data:'Dones'}, 'both', true)); } }""",
    "day_7_kid9_otowa": """{ tag: "versus", day: 7, title: "Chorros Destino", role: "kid9", xp: 15, location: "Kiyomizu", render: () => `<p class="mission-desc">Elige SOLO UN chorro.</p><button id="btn" class="btn-primary">Beber</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_7_kid9_otowa', {type:'text', data:'Bebido'})); } }""",
    "day_7_kid14_madera": """{ tag: "writing", day: 7, title: "Magia Madera", role: "kid14", xp: 15, location: "Kiyomizu", render: () => `<p class="mission-desc">Explica cómo aguanta sin clavos.</p><textarea id="t"></textarea><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_7_kid14_madera', {type:'text', data:document.getElementById('t').value})); } }""",
    "day_7_kid14_anti_seismic": """{ tag: "game", day: 7, title: "Anti-Sismo (G)", role: "kid14", xp: 20, location: "Kiyomizu", render: () => `<div class="level-container"><div id="bub" class="bubble"></div></div><button id="btn" class="btn-primary">Empezar</button><button id="btnV" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const b=document.getElementById('bub'); const btnS=document.getElementById('btn'); const btnV=document.getElementById('btnV'); let t=15; let act=false; window.addEventListener('deviceorientation', (e) => { if(act) b.style.transform = 'translate(calc(-50% + '+(e.gamma*2)+'px), calc(-50% + '+(e.beta*2)+'px))'; }); btnS.addEventListener('click', () => { act=true; btnS.classList.add('hidden'); setInterval(()=> { if(act){t--; if(t<=0){act=false; btnV.classList.remove('hidden');}} },1000); }); btnV.addEventListener('click', () => submitMission('day_7_kid14_anti_seismic', {type:'text', data:'Estable'})); } }""",

    "day_8_kid9_buda": """{ tag: "photo", day: 8, title: "Buda Gracioso", role: "kid9", xp: 15, location: "Otagi", render: () => `<button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_8_kid9_buda', {type:'text', data:'Foto'})); } }""",
    "day_8_kid14_twin": """{ tag: "writing", day: 8, title: "Gemelo Perdido", role: "kid14", xp: 15, location: "Otagi", render: () => `<input id="t"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_8_kid14_twin', {type:'text', data:document.getElementById('t').value})); } }""",
    "day_8_kid9_guardian": """{ tag: "photo", day: 8, title: "Guardián Estanque", role: "kid9", xp: 15, location: "Tenryu-ji", render: () => `<button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_8_kid9_guardian', {type:'text', data:'Foto'})); } }""",
    "day_8_kid14_bamboo_eng": """{ tag: "writing", day: 8, title: "Ingeniero Bosque", role: "kid14", xp: 15, location: "Arashiyama", render: () => `<input type="number" id="n"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_8_kid14_bamboo_eng', {type:'number', data:document.getElementById('n').value})); } }""",
    "day_8_kid14_codigo": """{ tag: "writing", day: 8, title: "El Código del Jardín", role: "kid14", xp: 20, location: "Tenryu-ji", render: () => `<input id="e1"><input id="e2"><input id="e3"><button id="b" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('b').addEventListener('click', () => submitMission('day_8_kid14_codigo', {type:'text', data:'Interpretación'})); } }""",
    "day_8_kid9_rake": """{ tag: "writing", day: 8, title: "Rastrillo Zen", role: "kid9", xp: 15, location: "Tenryu-ji", render: () => `<canvas id="rake" style="height:150px; width:100%; border:1px solid #ccc;"></canvas><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_8_kid9_rake', {type:'text', data:'Patron'})); } }""",
    "day_8_fam_silencio": """{ tag: "audio", day: 8, title: "Silencio Competitivo", role: "both", xp: 20, location: "Arashiyama", render: () => `<button id="b1">Grab A</button><button id="b2">Grab B</button><button id="b" class="btn-primary">Votar y Enviar</button>`, attachEvents: () => { document.getElementById('b').addEventListener('click', () => submitMission('day_8_fam_silencio', {type:'text', data:'Audio'}, 'both', true)); } }""",
    "day_8_kid9_drum": """{ tag: "audio", day: 8, title: "Tambor Bambú", role: "kid9", xp: 15, location: "Arashiyama", render: () => `<button id="btn-cam" class="btn-secondary">🎤 Grabar</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_8_kid9_drum', {type:'text', data:'Audio'})); } }""",
    "day_8_kid14_haiku": """{ tag: "writing", day: 8, title: "Maestro Haiku", role: "kid14", xp: 15, location: "Tenryu-ji", render: () => `<textarea id="t"></textarea><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_8_kid14_haiku', {type:'text', data:document.getElementById('t').value})); } }""",
    "day_8_kid14_wave_sync": """{ tag: "game", day: 8, title: "Sincro Ondas (G)", role: "kid14", xp: 20, location: "Arashiyama", render: () => `<canvas id="wc" class="wave-canvas"></canvas><input type="range" id="sl" min="0.01" max="0.1" step="0.01"><button id="btn" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const c=document.getElementById('wc'); const ctx=c.getContext('2d'); const s=document.getElementById('sl'); const b=document.getElementById('btn'); const loop=() => { ctx.clearRect(0,0,c.width,c.height); ctx.beginPath(); ctx.strokeStyle='#2ecc71'; for(let x=0;x<c.width;x++) ctx.lineTo(x,100+40*Math.sin(x*0.05)); ctx.stroke(); ctx.beginPath(); ctx.strokeStyle='#e74c3c'; for(let x=0;x<c.width;x++) ctx.lineTo(x,100+40*Math.sin(x*s.value)); ctx.stroke(); if(Math.abs(s.value-0.05)<0.01) b.classList.remove('hidden'); requestAnimationFrame(loop); }; loop(); b.addEventListener('click', () => submitMission('day_8_kid14_wave_sync', {type:'text', data:'Sincro'})); } }""",

    "day_9_kid14_torii_count": """{ tag: "writing", day: 9, title: "Código Torii", role: "kid14", xp: 15, location: "Fushimi", render: () => `<input type="number" id="n"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_9_kid14_torii_count', {type:'number', data:document.getElementById('n').value})); } }""",
    "day_9_kid9_kinkaku_mirror": """{ tag: "photo", day: 9, title: "Espejo Oro", role: "kid9", xp: 15, location: "Kinkaku", render: () => `<button id="btn-cam" class="btn-secondary">📸 Foto</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_9_kid9_kinkaku_mirror', {type:'text', data:'Foto'})); } }""",
    "day_9_kid14_heart": """{ tag: "sensors", day: 9, title: "Latido Montaña", role: "kid14", xp: 15, location: "Fushimi", render: () => `<input type="number" id="n"><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_9_kid14_heart', {type:'number', data:document.getElementById('n').value})); } }""",
    "day_9_kid9_inari_kitsune": """{ tag: "photo", day: 9, title: "Caza 3 Kitsune", role: "kid9", xp: 25, location: "Fushimi", render: () => `<button id="btn-cam" class="btn-secondary">📸 Fotos</button>`, attachEvents: () => { document.getElementById('btn-cam').addEventListener('click', () => submitMission('day_9_kid9_inari_kitsune', {type:'text', data:'Kitsunes'})); } }""",
    "day_9_kid9_zorro": """{ tag: "video", day: 9, title: "El Zorro Infiltrado", role: "kid9", xp: 25, location: "Fushimi", render: () => `<input type="file" accept="video/*" capture="environment"><button id="b" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('b').addEventListener('click', () => submitMission('day_9_kid9_zorro', {type:'text', data:'Zorro'})); } }""",
    "day_9_kid14_phoenix": """{ tag: "writing", day: 9, title: "Física Fénix", role: "kid14", xp: 15, location: "Kinkaku", render: () => `<textarea id="t"></textarea><button id="btn" class="btn-primary">Responder</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_9_kid14_phoenix', {type:'text', data:document.getElementById('t').value})); } }""",
    "day_9_kid14_gravity": """{ tag: "versus", day: 9, title: "Piedra Gravedad", role: "kid14", xp: 15, location: "Fushimi", render: () => `<button id="bm" class="btn-primary">Más</button><button id="bl" class="btn-secondary">Menos</button>`, attachEvents: () => { document.getElementById('bl').addEventListener('click', () => submitMission('day_9_kid14_gravity', {type:'text', data:'Menos'})); document.getElementById('bm').addEventListener('click', () => submitMission('day_9_kid14_gravity', {type:'text', data:'Más'})); } }""",
    "day_9_kid14_angulo": """{ tag: "photo", day: 9, title: "Ángulo Imposible", role: "kid14", xp: 20, location: "Kinkaku", render: () => `<input type="file" capture="environment"><input type="range" min="1" max="10"><button id="b" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('b').addEventListener('click', () => submitMission('day_9_kid14_angulo', {type:'text', data:'Foto'})); } }""",
    "day_9_kid9_scratch": """{ tag: "game", day: 9, title: "Limpia Reflejo (G)", role: "kid9", xp: 20, location: "Kinkaku", render: () => `<div class="scratch-container"><canvas id="sc" class="scratch-canvas"></canvas></div><button id="btn" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const c=document.getElementById('sc'); const ctx=c.getContext('2d'); const b=document.getElementById('btn'); ctx.fillStyle='#78909c'; ctx.fillRect(0,0,c.width,c.height); let s=0; c.addEventListener('touchmove', (e) => { ctx.globalCompositeOperation='destination-out'; ctx.beginPath(); ctx.arc(e.touches[0].clientX-c.offsetLeft, e.touches[0].clientY-c.offsetTop, 20, 0, 6.28); ctx.fill(); s++; if(s>50) b.classList.remove('hidden'); }); b.addEventListener('click', () => submitMission('day_9_kid9_scratch', {type:'text', data:'OK'})); } }""",
    "day_9_kid14_torii": """{ tag: "game", day: 9, title: "Laberinto Torii (G)", role: "kid14", xp: 25, location: "Fushimi", render: () => `<div class="torii-grid">${Array(9).fill(0).map((_,i)=>`<div class="tp" data-r="0" style="border:1px solid #ccc; height:60px;">⛩️</div>`).join('')}</div><button id="btn" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const ps=document.querySelectorAll('.tp'); const b=document.getElementById('btn'); let count=0; ps.forEach(p => p.addEventListener('click', () => { p.dataset.r=parseInt(p.dataset.r)+90; p.style.transform='rotate('+p.dataset.r+'deg)'; count++; if(count>5) b.classList.remove('hidden'); })); b.addEventListener('click', () => submitMission('day_9_kid14_torii', {type:'text', data:'OK'})); } }""",

    "day_10_kid14_nishiki": """{ tag: "writing", day: 10, title: "Dilema Chef", role: "kid14", xp: 15, location: "Nishiki", render: () => `<textarea id="t"></textarea><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_10_kid14_nishiki', {type:'text', data:document.getElementById('t').value})); } }""",
    "day_10_kid9_nishiki": """{ tag: "economy", day: 10, title: "Maestro Chatarra", role: "kid9", xp: 15, location: "Nishiki", render: () => `<button id="btn" class="btn-primary">Pagado</button>`, attachEvents: () => { document.getElementById('btn').addEventListener('click', () => submitMission('day_10_kid9_nishiki', {type:'text', data:'OK'})); } }""",
    "day_10_fam_sayonara": """{ tag: "writing", day: 10, title: "Sayonara Kioto", role: "both", xp: 30, location: "Despedida", render: () => `<textarea id="t"></textarea><button id="btn" class="btn-primary">Enviar</button>`, attachEvents: (role) => { document.getElementById('btn').addEventListener('click', () => submitMission('day_10_fam_sayonara', {type:'text', data:document.getElementById('t').value}, role, true)); } }""",
    "day_10_kid9_bento": """{ tag: "game", day: 10, title: "Maestro Bento (G)", role: "kid9", xp: 20, location: "Nishiki", render: () => `<div class="bento-tray"><div class="bento-slot">🍱</div></div><div class="ingredient" style="font-size:2rem;">🍱</div><button id="btn" class="btn-primary hidden">Enviar</button>`, attachEvents: () => { const ing=document.querySelector('.ingredient'); const b=document.getElementById('btn'); ing.addEventListener('touchmove', (e) => { ing.style.position='fixed'; ing.style.left=e.touches[0].clientX+'px'; ing.style.top=e.touches[0].clientY+'px'; b.classList.remove('hidden'); }); b.addEventListener('click', () => submitMission('day_10_kid9_bento', {type:'text', data:'OK'})); } }"""
}

# Construir bloque MISSIONS_CONFIG (Reconstrucción total para evitar errores de f-string)
config_lines = []
for k, v in MISSIONS.items():
    config_lines.append(f'    "{k}": {v}')

new_config_block = "const MISSIONS_CONFIG = {\n" + ",\n".join(config_lines) + "\n};"
new_content = re.sub(r'const MISSIONS_CONFIG = \{.*?\n\};', new_config_block, content, flags=re.DOTALL)

with open('app.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("MISSIONS_CONFIG actualizado con TODAS las misiones y las nuevas lógicas de Días 6-9.")
